#!/bin/bash

ACTION=$(echo "$1" | tr '[:upper:]' '[:lower:]')

if [ -z "$ACTION" ]; then
    echo "Usage: volume [up | down | power]"
    exit 1
fi

case "$ACTION" in
    "up")
        echo "Increasing volume..."
        adb shell input keyevent 24
        ;;
    "down")
        echo "Decreasing volume..."
        adb shell input keyevent 25
        ;;
    "power")
        echo "Toggling power button..."
        adb shell input keyevent 26
        ;;
    *)
        echo "Unknown command: $ACTION"
        echo "Usage: volume [up | down | power]"
        exit 1
        ;;
esac
